server:
  port: 8082
spring:
  application:
    name: spring-boot-rabbitmq-consumer
  rabbitmq:
    host: 39.97.3.60
    port: 5672
    username: Ringo
    password: 123
    virtual-host: /
    listener:
      simple:
        acknowledge-mode: manual # 手动 ack
        concurrency: 1  # 最小消费者数量
        max-concurrency: 1 # 最大消费者数量
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://39.97.3.60/test_rabbitmq?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 333
    type: com.zaxxer.hikari.HikariDataSource
  redis:
    host: 39.97.3.60
    port: 6379
    database: 1